/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.usep.clinic.management.system.gui;

import com.usep.clinic.management.system.AppContext;
import com.formdev.flatlaf.FlatLightLaf;
import com.usep.clinic.management.system.model.enums.Role;
import com.usep.clinic.management.system.service.*;
import java.awt.*;
import javax.swing.JButton;
import com.formdev.flatlaf.ui.FlatRoundBorder;
import javax.swing.JOptionPane;

/**
 *
 * @author Skrimp
 */
public class LoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        FlatLightLaf.setup();
        initComponents();
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        loginSidebarBtn = new javax.swing.JButton();
        registerSidebarBtn = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        main = new javax.swing.JPanel();
        loginForm = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        loginFormPanel = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        usernamePanel = new javax.swing.JPanel();
        usernameLbl = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        pwPanel = new javax.swing.JPanel();
        pwLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        rolePanel = new javax.swing.JPanel();
        roleLbl = new javax.swing.JLabel();
        roleCombobox = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        loginBtn = new javax.swing.JButton();
        footerPanel = new javax.swing.JPanel();
        footerTxt = new javax.swing.JLabel();
        footerTxtBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(AppContext.APP_NAME);
        setPreferredSize(new java.awt.Dimension(1012, 720));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        sidebar.setMaximumSize(new java.awt.Dimension(250, 312));
        sidebar.setMinimumSize(new java.awt.Dimension(250, 312));
        sidebar.setPreferredSize(new java.awt.Dimension(250, 312));
        sidebar.setLayout(new java.awt.BorderLayout());

        title.setBackground(new java.awt.Color(112, 164, 216));
        title.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 20, 10));
        title.setLayout(new javax.swing.BoxLayout(title, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel1.setText("Clinic");
        jLabel1.setAlignmentX(0.5F);
        title.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel2.setText("Management");
        jLabel2.setAlignmentX(0.5F);
        title.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel3.setText("System");
        jLabel3.setAlignmentX(0.5F);
        title.add(jLabel3);

        sidebar.add(title, java.awt.BorderLayout.NORTH);

        controlPanel.setBackground(new java.awt.Color(201, 220, 238));
        controlPanel.setLayout(new javax.swing.BoxLayout(controlPanel, javax.swing.BoxLayout.Y_AXIS));
        controlPanel.add(filler2);

        loginSidebarBtn.setBackground(new java.awt.Color(200, 219, 237));
        loginSidebarBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        loginSidebarBtn.setText("Login");
        loginSidebarBtn.setAlignmentX(0.5F);
        loginSidebarBtn.setBorderPainted(false);
        loginSidebarBtn.setMaximumSize(new java.awt.Dimension(300, 27));
        loginSidebarBtn.setOpaque(true);
        loginSidebarBtn.setPreferredSize(new java.awt.Dimension(79, 75));
        loginSidebarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSidebarBtnActionPerformed(evt);
            }
        });
        controlPanel.add(loginSidebarBtn);

        registerSidebarBtn.setBackground(new java.awt.Color(200, 219, 237));
        registerSidebarBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        registerSidebarBtn.setText("Register");
        registerSidebarBtn.setAlignmentX(0.5F);
        registerSidebarBtn.setBorderPainted(false);
        registerSidebarBtn.setMaximumSize(new java.awt.Dimension(300, 27));
        registerSidebarBtn.setOpaque(true);
        registerSidebarBtn.setPreferredSize(new java.awt.Dimension(79, 75));
        registerSidebarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerSidebarBtnActionPerformed(evt);
            }
        });
        controlPanel.add(registerSidebarBtn);
        controlPanel.add(filler1);

        sidebar.add(controlPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(sidebar, java.awt.BorderLayout.WEST);

        main.setToolTipText("");
        main.setMinimumSize(new java.awt.Dimension(227, 312));
        main.setLayout(new java.awt.GridBagLayout());

        loginForm.setBackground(new java.awt.Color(255, 255, 255));
        loginForm.setMaximumSize(new java.awt.Dimension(360, 600));
        loginForm.setMinimumSize(new java.awt.Dimension(360, 400));
        loginForm.setPreferredSize(new java.awt.Dimension(360, 500));
        loginForm.setLayout(new java.awt.BorderLayout());

        heading.setBackground(new java.awt.Color(255, 255, 255));
        heading.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        heading.setText("Login");
        heading.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        heading.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 35, 5, 20));
        loginForm.add(heading, java.awt.BorderLayout.NORTH);

        loginFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginFormPanel.setMaximumSize(new java.awt.Dimension(32767, 280));
        loginFormPanel.setOpaque(false);
        loginFormPanel.setLayout(new javax.swing.BoxLayout(loginFormPanel, javax.swing.BoxLayout.Y_AXIS));
        loginFormPanel.add(filler5);

        usernamePanel.setMaximumSize(new java.awt.Dimension(595, 60));
        usernamePanel.setMinimumSize(new java.awt.Dimension(595, 70));
        usernamePanel.setOpaque(false);
        usernamePanel.setPreferredSize(new java.awt.Dimension(595, 80));

        usernameLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usernameLbl.setLabelFor(usernameField);
        usernameLbl.setText("Username");
        usernameLbl.setAlignmentX(1.0F);
        usernameLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        usernameLbl.setPreferredSize(new java.awt.Dimension(290, 20));
        usernamePanel.add(usernameLbl);

        usernameField.setBackground(new Color(102,102,102,0));
        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usernameField.setMaximumSize(new java.awt.Dimension(290, 50));
        usernameField.setMinimumSize(new java.awt.Dimension(128, 50));
        usernameField.setName(""); // NOI18N
        usernameField.setPreferredSize(new java.awt.Dimension(290, 50));
        usernamePanel.add(usernameField);

        loginFormPanel.add(usernamePanel);
        loginFormPanel.add(filler6);

        pwPanel.setMaximumSize(new java.awt.Dimension(595, 60));
        pwPanel.setMinimumSize(new java.awt.Dimension(595, 70));
        pwPanel.setOpaque(false);
        pwPanel.setPreferredSize(new java.awt.Dimension(595, 80));

        pwLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pwLabel.setLabelFor(passwordField);
        pwLabel.setText("Password");
        pwLabel.setPreferredSize(new java.awt.Dimension(290, 20));
        pwPanel.add(pwLabel);

        passwordField.setBackground(new Color(102,102,102,0));
        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        passwordField.setMaximumSize(new java.awt.Dimension(290, 50));
        passwordField.setMinimumSize(new java.awt.Dimension(290, 50));
        passwordField.setPreferredSize(new java.awt.Dimension(290, 50));
        pwPanel.add(passwordField);

        loginFormPanel.add(pwPanel);
        loginFormPanel.add(filler4);

        rolePanel.setMaximumSize(new java.awt.Dimension(595, 60));
        rolePanel.setMinimumSize(new java.awt.Dimension(595, 70));
        rolePanel.setOpaque(false);
        rolePanel.setPreferredSize(new java.awt.Dimension(595, 80));

        roleLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        roleLbl.setLabelFor(passwordField);
        roleLbl.setText("Role");
        roleLbl.setPreferredSize(new java.awt.Dimension(290, 20));
        rolePanel.add(roleLbl);

        roleCombobox.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        roleCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Doctor", "Nurse" }));
        roleCombobox.setPreferredSize(new java.awt.Dimension(290, 50));
        roleCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleComboboxActionPerformed(evt);
            }
        });
        rolePanel.add(roleCombobox);

        rolePanel.setVisible(false);

        loginFormPanel.add(rolePanel);

        filler3.setVisible(false);
        loginFormPanel.add(filler3);

        loginBtn.setBackground(new java.awt.Color(201, 220, 238));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setAlignmentX(0.5F);
        loginBtn.setBorderPainted(false);
        loginBtn.setMaximumSize(new java.awt.Dimension(290, 50));
        loginBtn.setMinimumSize(new java.awt.Dimension(290, 50));
        loginBtn.setPreferredSize(new java.awt.Dimension(290, 50));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginFormPanel.add(loginBtn);

        loginForm.add(loginFormPanel, java.awt.BorderLayout.CENTER);

        footerPanel.setBackground(new java.awt.Color(255, 255, 255));
        footerPanel.setMinimumSize(new java.awt.Dimension(275, 60));
        footerPanel.setOpaque(false);
        footerPanel.setPreferredSize(new java.awt.Dimension(360, 60));
        footerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        footerTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerTxt.setText("No account yet?");
        footerTxt.setAlignmentY(0.0F);
        footerTxt.setMaximumSize(new java.awt.Dimension(100, 16));
        footerPanel.add(footerTxt);

        footerTxtBtn.setForeground(new java.awt.Color(51, 51, 255));
        footerTxtBtn.setText("Register here");
        footerTxtBtn.setAlignmentY(0.0F);
        footerTxtBtn.setContentAreaFilled(false);
        footerTxtBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        footerTxtBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                footerTxtBtnMouseEntered(evt);
            }
        });
        footerTxtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                footerTxtBtnActionPerformed(evt);
            }
        });
        footerPanel.add(footerTxtBtn);

        loginForm.add(footerPanel, java.awt.BorderLayout.PAGE_END);

        main.add(loginForm, new java.awt.GridBagConstraints());

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:

        if (getWidth() < 630){
            sidebar.setVisible(false);
        } else{
            sidebar.setVisible(true);
        }
    }//GEN-LAST:event_formComponentResized

    private void loginSidebarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSidebarBtnActionPerformed
        // TODO add your handling code here:
        isLoggingIn = true;
        switchForm();
    }//GEN-LAST:event_loginSidebarBtnActionPerformed

    private void registerSidebarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerSidebarBtnActionPerformed
        // TODO add your handling code here:
        isLoggingIn = false;
        switchForm();
    }//GEN-LAST:event_registerSidebarBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
       
        
        try{
            String username = usernameField.getText().trim();
            String password = String.valueOf(passwordField.getPassword()).trim();
            
            if (isLoggingIn){
                
                if (!AppContext.getAuthService().attemptLogin(username, password)){
                    JOptionPane.showMessageDialog(null,"Invalid credentials!", "Login failed",JOptionPane.WARNING_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Login successful!", "Login successful", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    new MainWindow();
                }
                
                return;
            }
            
            Role role = Role.valueOf( 
                    ((String) roleCombobox
                            .getSelectedItem())
                            .trim()
                            .toUpperCase()
            );
            System.out.println(role);
            AppContext.getAuthService().registerUser(username, password, role);
            JOptionPane.showMessageDialog(null, "Registration successful!", "Registration successful", JOptionPane.INFORMATION_MESSAGE);
            isLoggingIn = true;
            switchForm();
            
        }
        catch (DuplicateEntityException | InvalidPasswordLengthException e){
            JOptionPane.showMessageDialog(null,e.getMessage(), "Register failed",JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e){
            
            
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void footerTxtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_footerTxtBtnActionPerformed
        // TODO add your handling code here:
        isLoggingIn = !isLoggingIn;
        switchForm();
    }//GEN-LAST:event_footerTxtBtnActionPerformed

    private void roleComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboboxActionPerformed

    private void footerTxtBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footerTxtBtnMouseEntered
        // TODO add your handling code here:
        footerTxtBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_footerTxtBtnMouseEntered

    private void switchForm(){
        usernameField.setText("");
        passwordField.setText("");
        if (isLoggingIn){
            heading.setText("Login");
            loginBtn.setText("Login");
            footerTxt.setText("No Account Yet?");
            footerTxtBtn.setText("Register here");
            
            rolePanel.setVisible(false);
            filler3.setVisible(false);
            return;
                    
        }
        
        loginBtn.setText("Register");
        heading.setText("Register");
        footerTxt.setText("Already have an account?");
        footerTxtBtn.setText("Sign in here");
        rolePanel.setVisible(true);
        filler3.setVisible(true);
        
    }
    
    
    // states
    private boolean isLoggingIn = true;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel footerTxt;
    private javax.swing.JButton footerTxtBtn;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginForm;
    private javax.swing.JPanel loginFormPanel;
    private javax.swing.JButton loginSidebarBtn;
    private javax.swing.JPanel main;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel pwLabel;
    private javax.swing.JPanel pwPanel;
    private javax.swing.JButton registerSidebarBtn;
    private javax.swing.JComboBox<String> roleCombobox;
    private javax.swing.JLabel roleLbl;
    private javax.swing.JPanel rolePanel;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel title;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
