/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.usep.clinic.management.system.gui;

import com.formdev.flatlaf.FlatLightLaf;
import com.usep.clinic.management.system.AppContext;

/**
 *
 * @author Skrimp
 */
public class MainWindow extends javax.swing.JFrame {

    
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        sidebarControl = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        sidebar = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 8));
        patientRecordsBtn = new javax.swing.JButton();
        inventoryBtn = new javax.swing.JButton();
        logbookBtn = new javax.swing.JButton();
        reportsBtn = new javax.swing.JButton();
        mainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(AppContext.APP_NAME);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1012, 720));
        setPreferredSize(new java.awt.Dimension(1012, 720));
        setSize(new java.awt.Dimension(1012, 720));
        getContentPane().setLayout(new java.awt.BorderLayout(2, 0));

        header.setBackground(new java.awt.Color(112, 164, 216));
        header.setMinimumSize(new java.awt.Dimension(237, 50));
        header.setPreferredSize(new java.awt.Dimension(612, 50));
        header.setRequestFocusEnabled(false);
        header.setLayout(new java.awt.BorderLayout());

        leftPanel.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.setOpaque(false);
        leftPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        sidebarControl.setBackground(new java.awt.Color(112, 164, 216));
        sidebarControl.setIcon(AppContext.BAR_ICON);
        sidebarControl.setBorderPainted(false);
        sidebarControl.setFocusPainted(false);
        sidebarControl.setPreferredSize(new java.awt.Dimension(40, 40));
        sidebarControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarControlActionPerformed(evt);
            }
        });
        leftPanel.add(sidebarControl);

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setText("Clinic Management System");
        leftPanel.add(title);

        header.add(leftPanel, java.awt.BorderLayout.CENTER);

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightPanel.setMinimumSize(new java.awt.Dimension(116, 50));
        rightPanel.setOpaque(false);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout1.setAlignOnBaseline(true);
        rightPanel.setLayout(flowLayout1);

        logoutBtn.setBackground(new java.awt.Color(112, 164, 216));
        logoutBtn.setIcon(AppContext.LOGOUT_ICON);
        logoutBtn.setAlignmentY(0.0F);
        logoutBtn.setBorderPainted(false);
        logoutBtn.setFocusPainted(false);
        logoutBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        rightPanel.add(logoutBtn);

        header.add(rightPanel, java.awt.BorderLayout.EAST);

        getContentPane().add(header, java.awt.BorderLayout.NORTH);

        sidebar.setBackground(new java.awt.Color(201, 220, 238));
        sidebar.setMaximumSize(new java.awt.Dimension(200, 81));
        sidebar.setMinimumSize(new java.awt.Dimension(200, 81));
        sidebar.setPreferredSize(new java.awt.Dimension(200, 394));
        sidebar.setVerifyInputWhenFocusTarget(false);
        sidebar.setLayout(new javax.swing.BoxLayout(sidebar, javax.swing.BoxLayout.Y_AXIS));
        sidebar.add(filler1);

        patientRecordsBtn.setBackground(new java.awt.Color(201, 220, 238));
        patientRecordsBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        patientRecordsBtn.setText("Patient Records");
        patientRecordsBtn.setAlignmentX(0.5F);
        patientRecordsBtn.setBorderPainted(false);
        patientRecordsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        patientRecordsBtn.setMaximumSize(new java.awt.Dimension(500, 50));
        patientRecordsBtn.setPreferredSize(new java.awt.Dimension(79, 50));
        patientRecordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientRecordsBtnActionPerformed(evt);
            }
        });
        sidebar.add(patientRecordsBtn);

        inventoryBtn.setBackground(new java.awt.Color(201, 220, 238));
        inventoryBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inventoryBtn.setText("Inventory");
        inventoryBtn.setAlignmentX(0.5F);
        inventoryBtn.setBorderPainted(false);
        inventoryBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventoryBtn.setMaximumSize(new java.awt.Dimension(500, 50));
        inventoryBtn.setPreferredSize(new java.awt.Dimension(79, 50));
        inventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryBtnActionPerformed(evt);
            }
        });
        sidebar.add(inventoryBtn);

        logbookBtn.setBackground(new java.awt.Color(201, 220, 238));
        logbookBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        logbookBtn.setText("Logbook");
        logbookBtn.setAlignmentX(0.5F);
        logbookBtn.setBorderPainted(false);
        logbookBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logbookBtn.setMaximumSize(new java.awt.Dimension(500, 50));
        logbookBtn.setPreferredSize(new java.awt.Dimension(79, 50));
        logbookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbookBtnActionPerformed(evt);
            }
        });
        sidebar.add(logbookBtn);

        reportsBtn.setBackground(new java.awt.Color(201, 220, 238));
        reportsBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        reportsBtn.setText("Reports");
        reportsBtn.setAlignmentX(0.5F);
        reportsBtn.setBorderPainted(false);
        reportsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reportsBtn.setMaximumSize(new java.awt.Dimension(500, 50));
        reportsBtn.setPreferredSize(new java.awt.Dimension(79, 50));
        reportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsBtnActionPerformed(evt);
            }
        });
        sidebar.add(reportsBtn);

        getContentPane().add(sidebar, java.awt.BorderLayout.WEST);

        mainContent.setBackground(new java.awt.Color(255, 255, 255));
        mainContent.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainContent, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sidebarControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarControlActionPerformed
        // TODO add your handling code here:
        sidebar.setVisible(!sidebar.isVisible());
    }//GEN-LAST:event_sidebarControlActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LoginWindow();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void patientRecordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientRecordsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientRecordsBtnActionPerformed

    private void reportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportsBtnActionPerformed

    private void inventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryBtnActionPerformed

    private void logbookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbookBtnActionPerformed

    }//GEN-LAST:event_logbookBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow();
            }
        });
       
        
    }

    //
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel header;
    private javax.swing.JButton inventoryBtn;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton logbookBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainContent;
    private javax.swing.JButton patientRecordsBtn;
    private javax.swing.JButton reportsBtn;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton sidebarControl;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
