/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.usep.clinic.management.system.gui;

import com.formdev.flatlaf.FlatLightLaf;
import com.usep.clinic.management.system.AppContext;

/**
 *
 * @author Skrimp
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        sidebarControl = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        sidebar = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        mainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(AppContext.APP_NAME);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1012, 720));
        setPreferredSize(new java.awt.Dimension(1012, 720));
        setSize(new java.awt.Dimension(1012, 720));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        header.setMinimumSize(new java.awt.Dimension(237, 50));
        header.setPreferredSize(new java.awt.Dimension(612, 50));
        header.setRequestFocusEnabled(false);
        header.setLayout(new java.awt.BorderLayout());

        leftPanel.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        sidebarControl.setIcon(AppContext.BAR_ICON);
        sidebarControl.setBorderPainted(false);
        sidebarControl.setFocusPainted(false);
        sidebarControl.setPreferredSize(new java.awt.Dimension(40, 40));
        sidebarControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarControlActionPerformed(evt);
            }
        });
        leftPanel.add(sidebarControl);

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setText("Clinic Management System");
        leftPanel.add(title);

        header.add(leftPanel, java.awt.BorderLayout.CENTER);

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightPanel.setMinimumSize(new java.awt.Dimension(116, 50));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout1.setAlignOnBaseline(true);
        rightPanel.setLayout(flowLayout1);

        logoutBtn.setIcon(AppContext.LOGOUT_ICON);
        logoutBtn.setAlignmentY(0.0F);
        logoutBtn.setBorderPainted(false);
        logoutBtn.setFocusPainted(false);
        logoutBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        rightPanel.add(logoutBtn);

        header.add(rightPanel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setMaximumSize(new java.awt.Dimension(200, 81));
        sidebar.setMinimumSize(new java.awt.Dimension(200, 81));
        sidebar.setPreferredSize(new java.awt.Dimension(200, 394));
        sidebar.setLayout(new javax.swing.BoxLayout(sidebar, javax.swing.BoxLayout.Y_AXIS));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Patient Records");
        jButton2.setAlignmentX(0.5F);
        jButton2.setBorderPainted(false);
        jButton2.setMaximumSize(new java.awt.Dimension(500, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(79, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        sidebar.add(jButton2);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Inventory");
        jButton3.setAlignmentX(0.5F);
        jButton3.setBorderPainted(false);
        jButton3.setMaximumSize(new java.awt.Dimension(500, 50));
        jButton3.setPreferredSize(new java.awt.Dimension(79, 50));
        sidebar.add(jButton3);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Logbook");
        jButton4.setAlignmentX(0.5F);
        jButton4.setBorderPainted(false);
        jButton4.setMaximumSize(new java.awt.Dimension(500, 50));
        jButton4.setPreferredSize(new java.awt.Dimension(79, 50));
        sidebar.add(jButton4);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Reports");
        jButton5.setAlignmentX(0.5F);
        jButton5.setBorderPainted(false);
        jButton5.setMaximumSize(new java.awt.Dimension(500, 50));
        jButton5.setPreferredSize(new java.awt.Dimension(79, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        sidebar.add(jButton5);

        getContentPane().add(sidebar, java.awt.BorderLayout.LINE_START);

        mainContent.setBackground(new java.awt.Color(255, 255, 255));
        mainContent.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainContent, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sidebarControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarControlActionPerformed
        // TODO add your handling code here:
        sidebar.setVisible(!sidebar.isVisible());
    }//GEN-LAST:event_sidebarControlActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton sidebarControl;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
